<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Enums\QuestionType;
use App\Models\Assignment;
use App\Models\Course;
use App\Models\Evaluation;
use App\Models\Module;
use App\Models\Question;
use App\Models\QuestionBank;
use App\Models\Resource;
use App\Services\Assessment\AssignmentManager;
use App\Services\Assessment\EvaluationManager;
use App\Services\Assessment\QuestionManager;
use App\Services\Content\ResourceManager;
use App\Services\Storage\MediaStorageService;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Seeds real, module-specific content onto the "Backend Development" course's 5 modules:
 * a YouTube walkthrough, a scheduled live session, three real instructional documents
 * (Word/PDF/PowerPoint, generated once and committed under content/backend-development/),
 * one realistic assignment, and one quiz with real questions — per module.
 *
 * This course is real production/demo data created outside the DatabaseSeeder's synthetic
 * courses (it is not generated by CourseFactory), so this seeder looks it up by slug rather
 * than assuming it exists — if it hasn't been created in this environment yet, it warns and
 * exits instead of failing the whole `db:seed` run.
 *
 * Idempotent: every resource/assignment/question-bank/question/evaluation is looked up by its
 * natural key (module + title, or bank + question text) before being created, and file uploads
 * reuse a deterministic storage path, so re-running this seeder never duplicates rows or files.
 * All writes for a single module happen inside one transaction (see DB::transaction below).
 */
final class BackendDevelopmentContentSeeder extends Seeder
{
    private const COURSE_SLUG = 'backend-development';

    private const CONTENT_DIR = __DIR__.'/content/backend-development';

    public function run(): void
    {
        $course = Course::where('slug', self::COURSE_SLUG)->first();

        if (! $course) {
            $this->command?->warn('No course with slug "'.self::COURSE_SLUG.'" found — skipping BackendDevelopmentContentSeeder.');

            return;
        }

        $modules = Module::where('course_id', $course->id)->orderBy('order_index')->get();
        $moduleContent = $this->moduleContent();

        foreach ($modules as $module) {
            $content = $moduleContent[$module->order_index] ?? null;

            if ($content === null) {
                continue;
            }

            DB::transaction(function () use ($course, $module, $content): void {
                $this->seedYoutubeResource($module, $content);
                $this->seedLiveSessionResource($module, $content);
                $this->seedDocumentResources($course, $module, $content);
                $this->seedAssignment($module, $content);
                $this->seedEvaluation($course, $module, $content);
            });
        }

        $this->command?->info('Backend Development content seeded for '.$modules->count().' modules.');
    }

    private function seedYoutubeResource(Module $module, array $content): void
    {
        $title = $content['topic'].' — Video Walkthrough';

        if (Resource::where('module_id', $module->id)->where('title', $title)->exists()) {
            return;
        }

        app(ResourceManager::class)->create($module, [
            'type' => 'external_link',
            'title' => $title,
            'description' => 'Real YouTube video: "'.$content['youtube']['title'].'". Directly relevant to '.$content['topic'].'.',
            'url' => $content['youtube']['url'],
        ]);
    }

    private function seedLiveSessionResource(Module $module, array $content): void
    {
        $title = 'Live Session: '.$content['topic'];

        if (Resource::where('module_id', $module->id)->where('title', $title)->exists()) {
            return;
        }

        app(ResourceManager::class)->create($module, [
            'type' => 'live_session',
            'title' => $title,
            'description' => 'Scheduled live session for this module, covering: '.$content['liveSessionTopic'].
                '. This is a placeholder meeting room — the real link is shared with the cohort ahead of the session.',
            'provider' => 'zoom',
            'meeting_url' => 'https://zoom.us/j/'.(8200000000 + $module->id).'?pwd=backenddev-module-'.$module->order_index,
            'scheduled_at' => now()->addWeeks($module->order_index)->next('Wednesday')->setTime(17, 0),
            'duration_minutes' => 60,
        ]);
    }

    private function seedDocumentResources(Course $course, Module $module, array $content): void
    {
        $mediaStorage = app(MediaStorageService::class);
        $resourceManager = app(ResourceManager::class);

        foreach ($content['documents'] as $doc) {
            $title = $content['topic'].' — '.$doc['label'];

            if (Resource::where('module_id', $module->id)->where('title', $title)->exists()) {
                continue;
            }

            $localPath = self::CONTENT_DIR.'/'.$doc['filename'];
            $bytes = file_get_contents($localPath);
            $sizeKb = (int) ceil(strlen($bytes) / 1024);

            // Deterministic path (not a random hash) so re-seeding overwrites the same object
            // on the storage disk instead of accumulating orphaned copies.
            $storagePath = "resources/{$course->id}/seed/{$doc['filename']}";
            $mediaStorage->putRaw($storagePath, $bytes);

            $resourceManager->create($module, [
                'type' => 'document',
                'title' => $title,
                'description' => $doc['description'],
                'file_url' => $storagePath,
                'file_type' => $doc['fileType'],
                'file_size_kb' => $sizeKb,
            ]);
        }
    }

    private function seedAssignment(Module $module, array $content): void
    {
        $title = $content['assignment']['title'];

        if (Assignment::where('module_id', $module->id)->where('title', $title)->exists()) {
            return;
        }

        app(AssignmentManager::class)->create($module, [
            'title' => $title,
            'instructions' => $content['assignment']['instructions'],
            'submission_type' => 'both',
            'due_at' => now()->addDays($content['assignment']['dueDays']),
            'allow_late' => true,
            'max_score' => 100,
        ]);
    }

    private function seedEvaluation(Course $course, Module $module, array $content): void
    {
        $evalTitle = $content['evaluation']['title'];

        if (Evaluation::where('module_id', $module->id)->where('title', $evalTitle)->exists()) {
            return;
        }

        $bankTitle = $content['topic'].' — Quiz Question Bank';
        $bank = QuestionBank::where('course_id', $course->id)->where('title', $bankTitle)->first()
            ?? QuestionBank::create(['course_id' => $course->id, 'title' => $bankTitle]);

        $questionManager = app(QuestionManager::class);
        $questionIds = [];

        foreach ($content['evaluation']['questions'] as $q) {
            $existing = Question::where('question_bank_id', $bank->id)->where('question_text', $q['text'])->first();

            if ($existing) {
                $questionIds[] = $existing->id;

                continue;
            }

            $options = match ($q['type']) {
                QuestionType::McqSingle->value => array_map(
                    fn (array $o) => ['option_text' => $o['text'], 'is_correct' => $o['correct']],
                    $q['options'],
                ),
                QuestionType::TrueFalse->value => [
                    ['option_text' => 'True', 'is_correct' => $q['correct'] === true],
                    ['option_text' => 'False', 'is_correct' => $q['correct'] === false],
                ],
                default => [],
            };

            $question = $questionManager->create($bank, [
                'type' => $q['type'],
                'question_text' => $q['text'],
                'points' => 1,
                'options' => $options,
            ]);

            $questionIds[] = $question->id;
        }

        app(EvaluationManager::class)->create($module, [
            'title' => $evalTitle,
            'description' => $content['evaluation']['description'],
            'instructions' => 'You have 20 minutes and need a score of 70% or higher to pass. You may attempt this quiz up to 3 times.',
            'pass_score' => 70.00,
            'max_attempts' => 3,
            'time_limit_minutes' => 20,
            'question_ids' => $questionIds,
        ]);
    }

    /**
     * Keyed by the module's order_index within the Backend Development course (1..5), matching
     * the 5 modules already created for that course. Question option order below always lists
     * the correct answer first for mcq_single questions except where noted, matching what
     * QuestionManager persists via order_index.
     *
     * @return array<int, array<string, mixed>>
     */
    private function moduleContent(): array
    {
        return [
            1 => [
                'topic' => 'Backend Development Fundamentals',
                'liveSessionTopic' => 'setting up a Laravel project and building your first route',
                'youtube' => [
                    'url' => 'https://www.youtube.com/watch?v=MOLZOXqaomM',
                    'title' => 'Learn Laravel from Scratch [FULL BOOTCAMP COURSE] — Laravel (official)',
                ],
                'documents' => [
                    ['label' => 'Lecture Notes (Word)', 'filename' => 'module-1-fundamentals-lecture-notes.docx', 'fileType' => 'docx', 'description' => 'Detailed lecture notes covering HTTP, PHP basics, Composer, and the Laravel request lifecycle, with code examples.'],
                    ['label' => 'Quick Reference (PDF)', 'filename' => 'module-1-fundamentals-quick-reference.pdf', 'fileType' => 'pdf', 'description' => 'One-page reference: HTTP methods, status codes, Laravel directories, and essential Artisan commands.'],
                    ['label' => 'Slide Deck (PowerPoint)', 'filename' => 'module-1-fundamentals-slides.pptx', 'fileType' => 'pptx', 'description' => 'Lecture slide deck summarizing client-server architecture, HTTP, and the Laravel request lifecycle.'],
                ],
                'assignment' => [
                    'title' => 'Build and Document a Minimal Laravel Route',
                    'instructions' => 'In your local copy of the course starter project, create a new GET route at /api/v1/greeting that accepts an optional "name" query parameter and returns a JSON response of the form {"message": "Hello, <name>!"} (default to "World" when no name is supplied). Implement it with a dedicated controller method — not a closure in routes/api.php. In a short write-up (200–400 words), explain, in your own words: (1) what happens between the browser sending the request and your controller method running, naming at least three concrete steps of the Laravel request lifecycle; (2) which HTTP status code your endpoint returns on success and why; and (3) one HTTP status code your endpoint should return if it were changed to require an API token, and why. Submit both your route/controller code (as a text submission or a linked file) and your written explanation.',
                    'dueDays' => 10,
                ],
                'evaluation' => [
                    'title' => 'Backend Fundamentals Check',
                    'description' => 'Tests understanding of the HTTP request/response cycle, PHP basics, Composer, and Laravel’s request lifecycle.',
                    'questions' => [
                        ['type' => 'mcq_single', 'text' => 'Which HTTP method is the correct choice for creating a brand-new resource, such as enrolling a student in a course?', 'options' => [
                            ['text' => 'POST', 'correct' => true], ['text' => 'GET', 'correct' => false], ['text' => 'DELETE', 'correct' => false], ['text' => 'PUT', 'correct' => false],
                        ]],
                        ['type' => 'mcq_single', 'text' => 'A client submits a form with a missing required field. Which HTTP status code should Laravel’s validator return by default?', 'options' => [
                            ['text' => '422 Unprocessable Entity', 'correct' => true], ['text' => '200 OK', 'correct' => false], ['text' => '404 Not Found', 'correct' => false], ['text' => '500 Internal Server Error', 'correct' => false],
                        ]],
                        ['type' => 'true_false', 'text' => 'In Laravel, routes/api.php is the file used to define stateless API routes, separate from routes/web.php.', 'correct' => true],
                        ['type' => 'mcq_single', 'text' => 'What is the primary purpose of Composer in a PHP project?', 'options' => [
                            ['text' => 'Managing dependencies and generating an autoloader', 'correct' => true], ['text' => 'Compiling PHP into machine code', 'correct' => false], ['text' => 'Running the production web server', 'correct' => false], ['text' => 'Minifying JavaScript assets', 'correct' => false],
                        ]],
                        ['type' => 'mcq_single', 'text' => 'Which status code correctly represents "the request succeeded and a new resource now exists"?', 'options' => [
                            ['text' => '201 Created', 'correct' => true], ['text' => '200 OK', 'correct' => false], ['text' => '204 No Content', 'correct' => false], ['text' => '302 Found', 'correct' => false],
                        ]],
                        ['type' => 'short_answer', 'text' => 'Name the PHP superglobal array that plain (framework-less) PHP uses to read query-string parameters from a GET request.'],
                    ],
                ],
            ],

            2 => [
                'topic' => 'Databases & Data Management',
                'liveSessionTopic' => 'writing migrations and Eloquent relationships for a course/module schema',
                'youtube' => [
                    'url' => 'https://www.youtube.com/watch?v=SeQ-HKsGJ_k',
                    'title' => 'Laravel Eloquent Relationships Full Tutorial — LaraPhant',
                ],
                'documents' => [
                    ['label' => 'Lecture Notes (Word)', 'filename' => 'module-2-databases-lecture-notes.docx', 'fileType' => 'docx', 'description' => 'Lecture notes on relational databases, SQL, Laravel migrations, and Eloquent relationships, with code examples.'],
                    ['label' => 'Quick Reference (PDF)', 'filename' => 'module-2-databases-quick-reference.pdf', 'fileType' => 'pdf', 'description' => 'One-page reference: SQL clauses, migration column types, and Eloquent relationship cheat sheet.'],
                    ['label' => 'Slide Deck (PowerPoint)', 'filename' => 'module-2-databases-slides.pptx', 'fileType' => 'pptx', 'description' => 'Lecture slide deck summarizing relational databases, migrations, and Eloquent.'],
                ],
                'assignment' => [
                    'title' => 'Model a Module–Resource Relationship',
                    'instructions' => 'Using the course’s existing "modules" and "resources" tables as your reference schema (a module has many resources; each resource belongs to one module), write: (1) a migration that would create a new "module_notes" table with columns id, module_id (foreign key to modules, cascade on delete), note (text), and timestamps; (2) the Eloquent relationship methods you would add — a hasMany "notes" on the Module model and a belongsTo "module" on a new ModuleNote model; and (3) one Eloquent query that returns all notes for module_id 2, ordered by newest first. Submit your migration file content, both model snippets, and the query as a text submission, along with 2–3 sentences explaining why the foreign key belongs on module_notes rather than on modules.',
                    'dueDays' => 10,
                ],
                'evaluation' => [
                    'title' => 'Databases & Data Management Check',
                    'description' => 'Tests understanding of relational database concepts, SQL, Laravel migrations, and Eloquent relationships.',
                    'questions' => [
                        ['type' => 'mcq_single', 'text' => 'In a one-to-many relationship between Course and Module, which table holds the foreign key?', 'options' => [
                            ['text' => 'modules', 'correct' => true], ['text' => 'courses', 'correct' => false], ['text' => 'Neither — it is stored in a pivot table', 'correct' => false], ['text' => 'Both tables store it', 'correct' => false],
                        ]],
                        ['type' => 'mcq_single', 'text' => 'Which Eloquent relationship method would you define on Module to represent "many modules can belong to many groups"?', 'options' => [
                            ['text' => 'belongsToMany', 'correct' => true], ['text' => 'hasMany', 'correct' => false], ['text' => 'belongsTo', 'correct' => false], ['text' => 'hasOne', 'correct' => false],
                        ]],
                        ['type' => 'true_false', 'text' => 'php artisan migrate:rollback re-applies every migration in the project from scratch.', 'correct' => false],
                        ['type' => 'mcq_single', 'text' => 'Which SQL clause is used to combine rows from two related tables based on a matching column?', 'options' => [
                            ['text' => 'JOIN', 'correct' => true], ['text' => 'WHERE', 'correct' => false], ['text' => 'GROUP BY', 'correct' => false], ['text' => 'ORDER BY', 'correct' => false],
                        ]],
                        ['type' => 'mcq_single', 'text' => 'What is the main purpose of a database factory in Laravel?', 'options' => [
                            ['text' => 'To define how to generate one fake-but-valid model instance', 'correct' => true], ['text' => 'To run scheduled jobs', 'correct' => false], ['text' => 'To validate incoming HTTP requests', 'correct' => false], ['text' => 'To cache query results', 'correct' => false],
                        ]],
                        ['type' => 'short_answer', 'text' => 'Name the Eloquent relationship method you would use on the "belongs to" side of a one-to-many relationship (e.g. Module → Course).'],
                    ],
                ],
            ],

            3 => [
                'topic' => 'Building REST APIs',
                'liveSessionTopic' => 'designing and testing a RESTful Laravel API with Postman',
                'youtube' => [
                    'url' => 'https://www.youtube.com/watch?v=L1owEfA9ioc',
                    'title' => 'How to Build API Resources | Laravel API Course — Code With Dary',
                ],
                'documents' => [
                    ['label' => 'Lecture Notes (Word)', 'filename' => 'module-3-rest-apis-lecture-notes.docx', 'fileType' => 'docx', 'description' => 'Lecture notes on REST principles, route design, resource controllers, validation, and API resources.'],
                    ['label' => 'Quick Reference (PDF)', 'filename' => 'module-3-rest-apis-quick-reference.pdf', 'fileType' => 'pdf', 'description' => 'One-page reference: RESTful route table, validation rules, and API status codes.'],
                    ['label' => 'Slide Deck (PowerPoint)', 'filename' => 'module-3-rest-apis-slides.pptx', 'fileType' => 'pptx', 'description' => 'Lecture slide deck summarizing REST design, controllers, validation, and API resources.'],
                ],
                'assignment' => [
                    'title' => 'Design and Build a Module Resource Endpoint',
                    'instructions' => 'Design a RESTful, versioned API endpoint for listing the resources (videos, documents, links, etc.) that belong to a single module: GET /api/v1/modules/{module}/resources. Write: (1) the route definition as it would appear in routes/api.php; (2) the controller method that returns a paginated JSON:API-style collection of the module’s resources using an API Resource class (sketch the toArray() shape you would return — at minimum id, type, title, and order_index); (3) a Form Request or inline validation rule for an optional "type" query parameter that, if present, must be one of the seven valid resource types. Submit your route, controller method, and resource class as a text/code submission, plus one sentence stating which HTTP status code the endpoint should return when {module} does not exist.',
                    'dueDays' => 10,
                ],
                'evaluation' => [
                    'title' => 'Building REST APIs Check',
                    'description' => 'Tests understanding of REST principles, route design, validation, and API resources.',
                    'questions' => [
                        ['type' => 'mcq_single', 'text' => 'Which HTTP verb + path combination correctly maps to a controller’s "store" action under REST conventions?', 'options' => [
                            ['text' => 'POST /courses', 'correct' => true], ['text' => 'GET /courses', 'correct' => false], ['text' => 'PATCH /courses/{id}', 'correct' => false], ['text' => 'DELETE /courses/{id}', 'correct' => false],
                        ]],
                        ['type' => 'true_false', 'text' => 'REST APIs are expected to be stateless — the server should not rely on stored session state between requests.', 'correct' => true],
                        ['type' => 'mcq_single', 'text' => 'What does Route::apiResource(\'courses\', CourseController::class) register?', 'options' => [
                            ['text' => 'The five standard RESTful routes (index, store, show, update, destroy)', 'correct' => true], ['text' => 'A single catch-all route for /courses', 'correct' => false], ['text' => 'Only the index and show routes', 'correct' => false], ['text' => 'A route with no controller binding', 'correct' => false],
                        ]],
                        ['type' => 'mcq_single', 'text' => 'When a Form Request’s validation rules fail, what does Laravel do by default in an API context?', 'options' => [
                            ['text' => 'Returns a 422 response with an errors object', 'correct' => true], ['text' => 'Silently ignores the invalid fields', 'correct' => false], ['text' => 'Redirects back to the previous page', 'correct' => false], ['text' => 'Throws a fatal PHP error', 'correct' => false],
                        ]],
                        ['type' => 'mcq_single', 'text' => 'What is the main benefit of using a JsonResource class instead of returning an Eloquent model directly?', 'options' => [
                            ['text' => 'It decouples the public API shape from the database columns', 'correct' => true], ['text' => 'It makes queries run faster', 'correct' => false], ['text' => 'It automatically creates database migrations', 'correct' => false], ['text' => 'It is required for routes to work at all', 'correct' => false],
                        ]],
                        ['type' => 'short_answer', 'text' => 'Name the artisan flag used with make:controller to scaffold the standard REST method stubs (index, store, show, update, destroy) automatically.'],
                    ],
                ],
            ],

            4 => [
                'topic' => 'Authentication & Authorization',
                'liveSessionTopic' => 'issuing Sanctum tokens and writing a Policy class',
                'youtube' => [
                    'url' => 'https://www.youtube.com/watch?v=iXrfSFEXd-M',
                    'title' => 'Sanctum - API authentication simplified — Laravel (official)',
                ],
                'documents' => [
                    ['label' => 'Lecture Notes (Word)', 'filename' => 'module-4-auth-lecture-notes.docx', 'fileType' => 'docx', 'description' => 'Lecture notes on authentication vs authorization, password hashing, Sanctum tokens, middleware, and policies.'],
                    ['label' => 'Quick Reference (PDF)', 'filename' => 'module-4-auth-quick-reference.pdf', 'fileType' => 'pdf', 'description' => 'One-page reference: auth vs authz, Sanctum setup steps, 401 vs 403, and the Gate/Policy cheat sheet.'],
                    ['label' => 'Slide Deck (PowerPoint)', 'filename' => 'module-4-auth-slides.pptx', 'fileType' => 'pptx', 'description' => 'Lecture slide deck summarizing authentication, Sanctum tokens, middleware, and policies.'],
                ],
                'assignment' => [
                    'title' => 'Secure a Module Endpoint with Sanctum and a Policy',
                    'instructions' => 'Take the module resources endpoint from Module 3 (GET /api/v1/modules/{module}/resources) and secure it: (1) add the auth:sanctum middleware to the route so only authenticated requests reach the controller; (2) write a ModulePolicy::view(User $user, Module $module) method that returns true only if the user is an admin, an instructor assigned to the module’s course, or a student enrolled in that course; (3) call $this->authorize(\'view\', $module) at the start of the controller method. Submit the updated route definition, the policy method, and the authorize() call, plus 2–3 sentences explaining what HTTP status code an unauthenticated request receives versus an authenticated-but-not-enrolled request, and why they differ.',
                    'dueDays' => 10,
                ],
                'evaluation' => [
                    'title' => 'Authentication & Authorization Check',
                    'description' => 'Tests understanding of authentication vs authorization, password hashing, Sanctum tokens, and policies.',
                    'questions' => [
                        ['type' => 'mcq_single', 'text' => 'Which term describes the process of verifying that a user is who they claim to be?', 'options' => [
                            ['text' => 'Authentication', 'correct' => true], ['text' => 'Authorization', 'correct' => false], ['text' => 'Validation', 'correct' => false], ['text' => 'Serialization', 'correct' => false],
                        ]],
                        ['type' => 'mcq_single', 'text' => 'What does Hash::make() do to a user’s password before it is stored?', 'options' => [
                            ['text' => 'Hashes it with bcrypt so it cannot be reversed', 'correct' => true], ['text' => 'Encrypts it reversibly with the app key', 'correct' => false], ['text' => 'Base64-encodes it', 'correct' => false], ['text' => 'Leaves it unchanged for faster comparisons', 'correct' => false],
                        ]],
                        ['type' => 'true_false', 'text' => 'A request can be authenticated (the user’s identity is known) and still receive a 403 Forbidden response.', 'correct' => true],
                        ['type' => 'mcq_single', 'text' => 'In Laravel Sanctum, how does an API client typically send its token on subsequent requests?', 'options' => [
                            ['text' => 'In an "Authorization: Bearer <token>" header', 'correct' => true], ['text' => 'As a cookie named "token"', 'correct' => false], ['text' => 'As a query string parameter named "auth"', 'correct' => false], ['text' => 'It is not required after login', 'correct' => false],
                        ]],
                        ['type' => 'mcq_single', 'text' => 'What is the purpose of a Policy class in Laravel?', 'options' => [
                            ['text' => 'To group authorization rules for a specific Eloquent model', 'correct' => true], ['text' => 'To define database migrations for a model', 'correct' => false], ['text' => 'To validate incoming HTTP request bodies', 'correct' => false], ['text' => 'To configure queue connections', 'correct' => false],
                        ]],
                        ['type' => 'short_answer', 'text' => 'Name the middleware alias commonly used to require a valid Sanctum token on a route.'],
                    ],
                ],
            ],

            5 => [
                'topic' => 'Advanced Backend Development',
                'liveSessionTopic' => 'queued jobs, scheduling, and a production deployment checklist',
                'youtube' => [
                    'url' => 'https://www.youtube.com/watch?v=37yTwf-M0Js',
                    'title' => 'Laravel 12 – Queues | How to Use Queues in Laravel for Background Jobs',
                ],
                'documents' => [
                    ['label' => 'Lecture Notes (Word)', 'filename' => 'module-5-advanced-lecture-notes.docx', 'fileType' => 'docx', 'description' => 'Lecture notes on file storage, mail, notifications, queues, scheduling, logging, security, and deployment.'],
                    ['label' => 'Quick Reference (PDF)', 'filename' => 'module-5-advanced-quick-reference.pdf', 'fileType' => 'pdf', 'description' => 'One-page reference: queue commands, scheduling frequency methods, security checklist, and deployment checklist.'],
                    ['label' => 'Slide Deck (PowerPoint)', 'filename' => 'module-5-advanced-slides.pptx', 'fileType' => 'pptx', 'description' => 'Lecture slide deck summarizing queues, scheduling, logging, security, and deployment.'],
                ],
                'assignment' => [
                    'title' => 'Queue a Certificate Email and Schedule a Cleanup Job',
                    'instructions' => 'Design (1) a queued job, SendCertificateEmailJob, that implements ShouldQueue and, given a Certificate model instance, sends the student a "certificate issued" email via a Mailable — show the job’s constructor and handle() method; (2) the one-line dispatch call a CertificateService would use to queue that job instead of sending the email inline; and (3) a scheduled task entry (as it would appear in routes/console.php) that runs a "purge old failed jobs" artisan command once daily. In 150–250 words, explain why sending the email inline during the HTTP request that issues the certificate would be a poor design choice, referencing what happens to the user-facing response time if the mail server is slow. Submit your code and written explanation.',
                    'dueDays' => 14,
                ],
                'evaluation' => [
                    'title' => 'Advanced Backend Development Check',
                    'description' => 'Tests understanding of queues, scheduling, logging, security practices, and deployment configuration.',
                    'questions' => [
                        ['type' => 'mcq_single', 'text' => 'What is the main benefit of dispatching a slow task (like sending an email) to a queued job instead of running it inline?', 'options' => [
                            ['text' => 'The HTTP response returns immediately instead of waiting on the slow task', 'correct' => true], ['text' => 'It makes the email content shorter', 'correct' => false], ['text' => 'It removes the need for a Mailable class', 'correct' => false], ['text' => 'It automatically retries failed HTTP requests', 'correct' => false],
                        ]],
                        ['type' => 'mcq_single', 'text' => 'Which artisan command starts a worker process that actually executes queued jobs?', 'options' => [
                            ['text' => 'php artisan queue:work', 'correct' => true], ['text' => 'php artisan migrate', 'correct' => false], ['text' => 'php artisan serve', 'correct' => false], ['text' => 'php artisan schedule:run', 'correct' => false],
                        ]],
                        ['type' => 'true_false', 'text' => 'Laravel’s task scheduler requires one cron entry per scheduled task.', 'correct' => false],
                        ['type' => 'mcq_single', 'text' => 'Why should APP_DEBUG be set to false in a production environment?', 'options' => [
                            ['text' => 'It prevents detailed error pages from leaking stack traces to users', 'correct' => true], ['text' => 'It speeds up the router', 'correct' => false], ['text' => 'It is required for queues to work', 'correct' => false], ['text' => 'It disables logging entirely', 'correct' => false],
                        ]],
                        ['type' => 'mcq_single', 'text' => 'What does listing fields in a model’s $fillable property protect against?', 'options' => [
                            ['text' => 'Mass-assignment of fields the caller should not be able to set', 'correct' => true], ['text' => 'SQL injection in raw queries', 'correct' => false], ['text' => 'Slow database queries', 'correct' => false], ['text' => 'Missing database migrations', 'correct' => false],
                        ]],
                        ['type' => 'short_answer', 'text' => 'Name the Laravel facade used to write structured messages to the configured log channels (e.g. ::error(), ::info()).'],
                    ],
                ],
            ],
        ];
    }
}
